[package]
name = "cyber-christmas-card"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
panic = "abort"
opt-level = 3
strip = true
codegen-units = 1

[dependencies]
bit-set = "0.8"
colored = "2.2"
rand = "0.8"
term_size = "0.3"